services:
  - type: web
    name: fin-api
    plan: free
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        value: db.wcmqmzjrncegrfmrkobm.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: m3LlGv2kvx6j8ifg
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGIN
        value: https://fin-frontend-6uvz.onrender.com
    healthCheckPath: /actuator/health

  - type: web
    name: fin-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://fintracker-api-ipq4.onrender.com
